# coding: utf-8

"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://openapi-generator.tech
"""

import re  # noqa: F401
import sys  # noqa: F401
import typing  # noqa: F401
import functools  # noqa: F401

from frozendict import frozendict  # noqa: F401

import decimal  # noqa: F401
from datetime import date, datetime  # noqa: F401
from frozendict import frozendict  # noqa: F401

from lightly.openapi_generated.swagger_client.schemas import (  # noqa: F401
    AnyTypeSchema,
    ComposedSchema,
    DictSchema,
    ListSchema,
    StrSchema,
    IntSchema,
    Int32Schema,
    Int64Schema,
    Float32Schema,
    Float64Schema,
    NumberSchema,
    UUIDSchema,
    DateSchema,
    DateTimeSchema,
    DecimalSchema,
    BoolSchema,
    BinarySchema,
    NoneSchema,
    none_type,
    Configuration,
    Unset,
    unset,
    ComposedBase,
    ListBase,
    DictBase,
    NoneBase,
    StrBase,
    IntBase,
    Int32Base,
    Int64Base,
    Float32Base,
    Float64Base,
    NumberBase,
    UUIDBase,
    DateBase,
    DateTimeBase,
    BoolBase,
    BinaryBase,
    Schema,
    _SchemaValidator,
    _SchemaTypeChecker,
    _SchemaEnumMaker
)


class JobStatusData(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    _required_property_names = set((
        'id',
        'status',
        'waitTimeTillNextPoll',
        'createdAt',
    ))

    @classmethod
    @property
    def id(cls) -> typing.Type['MongoObjectID']:
        return MongoObjectID

    @classmethod
    @property
    def datasetId(cls) -> typing.Type['MongoObjectID']:
        return MongoObjectID

    @classmethod
    @property
    def status(cls) -> typing.Type['JobState']:
        return JobState

    @classmethod
    @property
    def meta(cls) -> typing.Type['JobStatusMeta']:
        return JobStatusMeta
    waitTimeTillNextPoll = Int32Schema

    @classmethod
    @property
    def createdAt(cls) -> typing.Type['Timestamp']:
        return Timestamp

    @classmethod
    @property
    def lastModifiedAt(cls) -> typing.Type['Timestamp']:
        return Timestamp

    @classmethod
    @property
    def finishedAt(cls) -> typing.Type['Timestamp']:
        return Timestamp
    error = StrSchema
    
    
    class result(
        DictSchema
    ):
        _required_property_names = set((
        ))
    
        @classmethod
        @property
        def type(cls) -> typing.Type['JobResultType']:
            return JobResultType
    
        @classmethod
        @property
        def data(cls) -> typing.Type['GeneralJobResult']:
            return GeneralJobResult
    
    
        def __new__(
            cls,
            *args: typing.Union[dict, frozendict, ],
            data: typing.Union['GeneralJobResult', Unset] = unset,
            _configuration: typing.Optional[Configuration] = None,
            **kwargs: typing.Type[Schema],
        ) -> 'result':
            return super().__new__(
                cls,
                *args,
                data=data,
                _configuration=_configuration,
                **kwargs,
            )


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        id: id,
        status: status,
        waitTimeTillNextPoll: waitTimeTillNextPoll,
        createdAt: createdAt,
        datasetId: typing.Union['MongoObjectID', Unset] = unset,
        meta: typing.Union['JobStatusMeta', Unset] = unset,
        lastModifiedAt: typing.Union['Timestamp', Unset] = unset,
        finishedAt: typing.Union['Timestamp', Unset] = unset,
        error: typing.Union[error, Unset] = unset,
        result: typing.Union[result, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'JobStatusData':
        return super().__new__(
            cls,
            *args,
            id=id,
            status=status,
            waitTimeTillNextPoll=waitTimeTillNextPoll,
            createdAt=createdAt,
            datasetId=datasetId,
            meta=meta,
            lastModifiedAt=lastModifiedAt,
            finishedAt=finishedAt,
            error=error,
            result=result,
            _configuration=_configuration,
            **kwargs,
        )

from lightly.openapi_generated.swagger_client.model.general_job_result import GeneralJobResult
from lightly.openapi_generated.swagger_client.model.job_result_type import JobResultType
from lightly.openapi_generated.swagger_client.model.job_state import JobState
from lightly.openapi_generated.swagger_client.model.job_status_meta import JobStatusMeta
from lightly.openapi_generated.swagger_client.model.mongo_object_id import MongoObjectID
from lightly.openapi_generated.swagger_client.model.timestamp import Timestamp
