repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: detect-private-key      # check for private keys
  - id: check-added-large-files # prevent commit of files >500kB
    args: ['--maxkb=500']
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.7
  hooks:
    - id: ruff
      args: [--fix, --select, I]
    - id: ruff-format
