
input_dir: ''     # Path to the input directory.
lightly_dir: ''   # Path to the lightly directory.
host: 'localhost' # Hostname for serving the data.
port: 3456        # Port for serving the data.


defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .
