# coding: utf-8

"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.samples_api import SamplesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSamplesApi(unittest.TestCase):
    """SamplesApi unit test stubs"""

    def setUp(self):
        self.api = SamplesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_sample_by_id(self):
        """Test case for get_sample_by_id

        """
        pass

    def test_get_sample_image_read_url_by_id(self):
        """Test case for get_sample_image_read_url_by_id

        """
        pass

    def test_get_sample_image_write_url_by_id(self):
        """Test case for get_sample_image_write_url_by_id

        """
        pass

    def test_get_samples_by_dataset_id(self):
        """Test case for get_samples_by_dataset_id

        """
        pass

    def test_update_sample_by_id(self):
        """Test case for update_sample_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
