# coding: utf-8

"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import lightly.openapi_generated.lightly.openapi_generated.lightly.openapi_generated.swagger_client
from lightly.openapi_generated.lightly.openapi_generated.lightly.openapi_generated.swagger_client.models.annotation_offer_data import AnnotationOfferData  # noqa: E501
from lightly.openapi_generated.lightly.openapi_generated.lightly.openapi_generated.swagger_client.rest import ApiException


class TestAnnotationOfferData(unittest.TestCase):
    """AnnotationOfferData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnnotationOfferData(self):
        """Test AnnotationOfferData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lightly.openapi_generated.lightly.openapi_generated.lightly.openapi_generated.swagger_client.models.annotation_offer_data.AnnotationOfferData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
