# coding: utf-8

"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import lightly.openapi_generated.openapi_client
from lightly.openapi_generated.openapi_client.api.annotations_api import AnnotationsApi  # noqa: E501
from lightly.openapi_generated.openapi_client.rest import ApiException


class TestAnnotationsApi(unittest.TestCase):
    """AnnotationsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.annotations_api.AnnotationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_annotation_by_id(self):
        """Test case for get_annotation_by_id

        Get a Annotation by its ID  # noqa: E501
        """
        pass

    def test_get_annotations_by_dataset_id(self):
        """Test case for get_annotations_by_dataset_id

        Get all annotations of a dataset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
