# coding: utf-8

"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://openapi-generator.tech
"""

from lightly.openapi_generated.swagger_client.api_client import ApiClient
from lightly.openapi_generated.swagger_client.api.collaboration_api_endpoints.create_or_update_shared_access_config_by_dataset_id import CreateOrUpdateSharedAccessConfigByDatasetId
from lightly.openapi_generated.swagger_client.api.collaboration_api_endpoints.delete_shared_access_config_by_id import DeleteSharedAccessConfigById
from lightly.openapi_generated.swagger_client.api.collaboration_api_endpoints.get_shared_access_configs_by_dataset_id import GetSharedAccessConfigsByDatasetId


class CollaborationApi(
    CreateOrUpdateSharedAccessConfigByDatasetId,
    DeleteSharedAccessConfigById,
    GetSharedAccessConfigsByDatasetId,
    ApiClient,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
