# coding: utf-8

"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://openapi-generator.tech
"""

import unittest

import lightly.openapi_generated.swagger_client
from lightly.openapi_generated.swagger_client.model.tag_create_request import TagCreateRequest


class TestTagCreateRequest(unittest.TestCase):
    """TagCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_TagCreateRequest(self):
        """Test TagCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TagCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
