"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://openapi-generator.tech
"""


import unittest

import lightly.openapi_generated_with_other_gen.openapi_client
from lightly.openapi_generated_with_other_gen.openapi_client.api.annotations_api import AnnotationsApi  # noqa: E501


class TestAnnotationsApi(unittest.TestCase):
    """AnnotationsApi unit test stubs"""

    def setUp(self):
        self.api = AnnotationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_annotation_by_id(self):
        """Test case for get_annotation_by_id

        """
        pass

    def test_get_annotations_by_dataset_id(self):
        """Test case for get_annotations_by_dataset_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
