"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lightly.api.openapi_generated.swagger_client
from lightly.api.openapi_generated.swagger_client.model.datasource_raw_samples_data_row import DatasourceRawSamplesDataRow
globals()['DatasourceRawSamplesDataRow'] = DatasourceRawSamplesDataRow
from lightly.api.openapi_generated.swagger_client.model.datasource_raw_samples_data import DatasourceRawSamplesData


class TestDatasourceRawSamplesData(unittest.TestCase):
    """DatasourceRawSamplesData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDatasourceRawSamplesData(self):
        """Test DatasourceRawSamplesData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DatasourceRawSamplesData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
