"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lightly.api.openapi_generated.swagger_client
from lightly.api.openapi_generated.swagger_client.model.dimensionality_reduction_method import DimensionalityReductionMethod
from lightly.api.openapi_generated.swagger_client.model.embedding2d_coordinates import Embedding2dCoordinates
from lightly.api.openapi_generated.swagger_client.model.mongo_object_id import MongoObjectID
from lightly.api.openapi_generated.swagger_client.model.timestamp import Timestamp
globals()['DimensionalityReductionMethod'] = DimensionalityReductionMethod
globals()['Embedding2dCoordinates'] = Embedding2dCoordinates
globals()['MongoObjectID'] = MongoObjectID
globals()['Timestamp'] = Timestamp
from lightly.api.openapi_generated.swagger_client.model.embedding2d_data import Embedding2dData


class TestEmbedding2dData(unittest.TestCase):
    """Embedding2dData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmbedding2dData(self):
        """Test Embedding2dData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Embedding2dData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
