"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lightly.api.openapi_generated.swagger_client
from lightly.api.openapi_generated.swagger_client.model.dimensionality_reduction_method import DimensionalityReductionMethod
globals()['DimensionalityReductionMethod'] = DimensionalityReductionMethod
from lightly.api.openapi_generated.swagger_client.model.trigger2d_embedding_job_request import Trigger2dEmbeddingJobRequest


class TestTrigger2dEmbeddingJobRequest(unittest.TestCase):
    """Trigger2dEmbeddingJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrigger2dEmbeddingJobRequest(self):
        """Test Trigger2dEmbeddingJobRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Trigger2dEmbeddingJobRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
