"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lightly.api.openapi_generated.swagger_client
from lightly.api.openapi_generated.swagger_client.model.create_entity_response import CreateEntityResponse
from lightly.api.openapi_generated.swagger_client.model.mongo_object_id import MongoObjectID
from lightly.api.openapi_generated.swagger_client.model.tag_bit_mask_data import TagBitMaskData
from lightly.api.openapi_generated.swagger_client.model.tag_bit_mask_response import TagBitMaskResponse
globals()['CreateEntityResponse'] = CreateEntityResponse
globals()['MongoObjectID'] = MongoObjectID
globals()['TagBitMaskData'] = TagBitMaskData
globals()['TagBitMaskResponse'] = TagBitMaskResponse
from lightly.api.openapi_generated.swagger_client.model.tag_arithmetics_response import TagArithmeticsResponse


class TestTagArithmeticsResponse(unittest.TestCase):
    """TagArithmeticsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagArithmeticsResponse(self):
        """Test TagArithmeticsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TagArithmeticsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
