"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import lightly.api.openapi_generated.swagger_client
from lightly.api.openapi_generated.swagger_client.model.custom_sample_meta_data import CustomSampleMetaData
from lightly.api.openapi_generated.swagger_client.model.mongo_object_id import MongoObjectID
from lightly.api.openapi_generated.swagger_client.model.sample_data_base import SampleDataBase
from lightly.api.openapi_generated.swagger_client.model.sample_data_image_all_of import SampleDataImageAllOf
from lightly.api.openapi_generated.swagger_client.model.sample_meta_data import SampleMetaData
from lightly.api.openapi_generated.swagger_client.model.timestamp import Timestamp
globals()['CustomSampleMetaData'] = CustomSampleMetaData
globals()['MongoObjectID'] = MongoObjectID
globals()['SampleDataBase'] = SampleDataBase
globals()['SampleDataImageAllOf'] = SampleDataImageAllOf
globals()['SampleMetaData'] = SampleMetaData
globals()['Timestamp'] = Timestamp
from lightly.api.openapi_generated.swagger_client.model.sample_data_image import SampleDataImage


class TestSampleDataImage(unittest.TestCase):
    """SampleDataImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSampleDataImage(self):
        """Test SampleDataImage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SampleDataImage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
