# coding: utf-8

"""
    Lightly API

    Lightly.ai enables you to do self-supervised learning in an easy and intuitive way. The lightly.ai OpenAPI spec defines how one can interact with our REST API to unleash the full potential of lightly.ai  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@lightly.ai
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from lightly.openapi_generated.swagger_client.configuration import Configuration


class DockerRunState(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    STARTED = "STARTED"
    INITIALIZING = "INITIALIZING"
    CHECKING_CORRUPTNESS = "CHECKING_CORRUPTNESS"
    PRETAGGING = "PRETAGGING"
    INITIALIZING_OBJECT_CROPS = "INITIALIZING_OBJECT_CROPS"
    TRAINING = "TRAINING"
    EMBEDDING = "EMBEDDING"
    EMBEDDING_OBJECT_CROPS = "EMBEDDING_OBJECT_CROPS"
    COMPUTING_ACTIVE_LEARNING_SCORES = "COMPUTING_ACTIVE_LEARNING_SCORES"
    SAMPLING = "SAMPLING"
    EMBEDDING_FULL_IMAGES = "EMBEDDING_FULL_IMAGES"
    SAVING_RESULTS = "SAVING_RESULTS"
    UPLOADING_DATASET = "UPLOADING_DATASET"
    GENERATING_REPORT = "GENERATING_REPORT"
    UPLOADING_REPORT = "UPLOADING_REPORT"
    UPLOADED_REPORT = "UPLOADED_REPORT"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ABORTED = "ABORTED"

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self, _configuration=None):  # noqa: E501
        """DockerRunState - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DockerRunState, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DockerRunState):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DockerRunState):
            return True

        return self.to_dict() != other.to_dict()
