# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from lightly.openapi_generated_with_other_gen.openapi_client.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from lightly.openapi_generated_with_other_gen.openapi_client.model.annotation_data import AnnotationData
from lightly.openapi_generated_with_other_gen.openapi_client.model.annotation_meta_data import AnnotationMetaData
from lightly.openapi_generated_with_other_gen.openapi_client.model.annotation_offer_data import AnnotationOfferData
from lightly.openapi_generated_with_other_gen.openapi_client.model.annotation_state import AnnotationState
from lightly.openapi_generated_with_other_gen.openapi_client.model.api_error_code import ApiErrorCode
from lightly.openapi_generated_with_other_gen.openapi_client.model.api_error_response import ApiErrorResponse
from lightly.openapi_generated_with_other_gen.openapi_client.model.async_task_data import AsyncTaskData
from lightly.openapi_generated_with_other_gen.openapi_client.model.create_cf_bucket_activity_request import CreateCFBucketActivityRequest
from lightly.openapi_generated_with_other_gen.openapi_client.model.create_entity_response import CreateEntityResponse
from lightly.openapi_generated_with_other_gen.openapi_client.model.dataset_data import DatasetData
from lightly.openapi_generated_with_other_gen.openapi_client.model.dataset_type import DatasetType
from lightly.openapi_generated_with_other_gen.openapi_client.model.embedding_data import EmbeddingData
from lightly.openapi_generated_with_other_gen.openapi_client.model.image_type import ImageType
from lightly.openapi_generated_with_other_gen.openapi_client.model.initial_tag_create_request import InitialTagCreateRequest
from lightly.openapi_generated_with_other_gen.openapi_client.model.inline_object import InlineObject
from lightly.openapi_generated_with_other_gen.openapi_client.model.inline_response200 import InlineResponse200
from lightly.openapi_generated_with_other_gen.openapi_client.model.job_result_type import JobResultType
from lightly.openapi_generated_with_other_gen.openapi_client.model.job_state import JobState
from lightly.openapi_generated_with_other_gen.openapi_client.model.job_status_data import JobStatusData
from lightly.openapi_generated_with_other_gen.openapi_client.model.job_status_data_result import JobStatusDataResult
from lightly.openapi_generated_with_other_gen.openapi_client.model.mongo_object_id import MongoObjectID
from lightly.openapi_generated_with_other_gen.openapi_client.model.sample_data import SampleData
from lightly.openapi_generated_with_other_gen.openapi_client.model.sample_meta_data import SampleMetaData
from lightly.openapi_generated_with_other_gen.openapi_client.model.sampling_config import SamplingConfig
from lightly.openapi_generated_with_other_gen.openapi_client.model.sampling_config_stopping_condition import SamplingConfigStoppingCondition
from lightly.openapi_generated_with_other_gen.openapi_client.model.sampling_create_request import SamplingCreateRequest
from lightly.openapi_generated_with_other_gen.openapi_client.model.sampling_method import SamplingMethod
from lightly.openapi_generated_with_other_gen.openapi_client.model.tag_bit_mask_data import TagBitMaskData
from lightly.openapi_generated_with_other_gen.openapi_client.model.tag_change_data import TagChangeData
from lightly.openapi_generated_with_other_gen.openapi_client.model.tag_create_request import TagCreateRequest
from lightly.openapi_generated_with_other_gen.openapi_client.model.tag_data import TagData
from lightly.openapi_generated_with_other_gen.openapi_client.model.tag_filenames_data import TagFilenamesData
from lightly.openapi_generated_with_other_gen.openapi_client.model.tag_name import TagName
from lightly.openapi_generated_with_other_gen.openapi_client.model.write_csv_url_data import WriteCSVUrlData
