name: "Check Example Notebooks"

on:
  push:
    branches: [master]
    paths:
      - "examples/**/*.py"
  pull_request:
    branches: [master]
    paths:
      - "examples/**/*.py"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  convert-to-nbs:
    name: "Check Example Notebooks"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Set Up uv
        uses: astral-sh/setup-uv@v9
        with:
          version: 0.12.3
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set Up Environment
        run: make install-notebook
      - name: Check Notebooks Are Up To Date
        run: make test-notebooks
