name: "Convert Examples to Notebooks"

on:
  push:
    branches: [main]
    paths:
      - "examples/pytorch/**.py"
  pull_request:
    branches: [main]
    paths:
      - "examples/pytorch/**.py"
  workflow_dispatch:

jobs:
  convert-to-nbs:
    name: "Convert examples to notebooks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.7
      - name: Set Up Environment
        run: |
          make install-uv reset-venv
          source .venv/bin/activate
          uv pip install nbformat jupytext
      - name: Convert using Script
        run: |
          make generate-example-notebooks
      - name: Check for diff
        run: |
          git add examples/notebooks/
          if ! git diff --cached --exit-code; then
            echo "Notebooks have changed! Please commit the changes."
            exit 1
          fi
