name: Build and release lightly

on:
  push:
  release:
    types: [created]

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
    - name: Get latest release
      id: latest_release
      uses: kaliber5/action-get-release@v1
      with:
        token: ${{ github.token }}
        latest: true
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: refs/tags/`${ steps.get_release.outputs.name }`
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Build and release
      id: build_and_release
      run: git log -p -2
