on:
  push: # TODO: Remove me
  release:
    types: [created]

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.3.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${ steps.get_release.outputs.tag_name }
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Build and release
      id: build_and_release
      run: git log -p -2
